-- Grad Application 
SELECT p.BYU_ID AS APPLICANT, p.BYU_ID,p.NET_ID, ga.APPLY_YEAR_TERM, SUBSTR(ga.APPLY_YEAR_TERM,1,4) AS entering_class_of,
TO_CHAR(TO_NUMBER(SUBSTR(ga.APPLY_YEAR_TERM,1,4))+2) AS exp_graduation, ga.PROGRAM, ap.DESCRIPTION AS program_description,
    (SELECT MIN(gal.DATE_TIME_UPDATED) 
        FROM adm.GRAD_ADM_LOG gal 
        WHERE gal.PERSON_ID = p.PERSON_ID) AS application_start_date,
ga.DEPT_COMPLETE_DT,
CASE ga.APPLICATION_ST
    WHEN 'A' THEN 'Admit'
    WHEN 'D' THEN 'Deny'
    WHEN 'N' THEN 'No Show'
    WHEN 'P' THEN 'Provisional Admit'
    WHEN 'L' THEN 'Late'
    WHEN 'W' THEN 'Withdrawn'
    WHEN 'I' THEN 'In-process'
    ELSE NULL END AS committee_desc,
ga.UNIV_COMPLETE_DT,
ga.DEPOSIT_RECEIVED, aa.SUBMITTED_DATE_TIME, p.REST_OF_NAME || ' ' || p.SURNAME || ' - ' || ap.DESCRIPTION || ' - ' || ga.APPLY_YEAR_TERM AS name,
pcm.PROGRAM_ID AS edu_program_id, p.PERSON_ID, TO_CHAR(TO_NUMBER(SUBSTR(ga.APPLY_YEAR_TERM,1,4)) - EXTRACT(YEAR FROM p.DATE_OF_BIRTH)) AS est_age,
    (SELECT MAX(s.TEST_SCORE) 
        FROM STD_TEST_SCORES s 
        WHERE s.PERSON_ID = p.PERSON_ID AND TEST_TYPE = 'GMAT' AND SCORE_TYPE = 'COMP') AS gmat_test_score
FROM pro.PERSON p
JOIN adm.GRAD_APPLICATION ga ON (ga.PERSON_ID = p.PERSON_ID)
LEFT JOIN stdprgm.PROGRAM_ID_CODE_MAP pcm ON (pcm.PROGRAM_CODE = ga.PROGRAM AND ga.APPLY_YEAR_TERM BETWEEN pcm.EFF_YEAR_TERM AND pcm.EXP_YEAR_TERM)
JOIN stdprgm.ACADEMIC_PROGRAM ap ON (ap.PROGRAM_ID = pcm.PROGRAM_ID AND CURRENT_DATE >= ap.EFFECTIVE_DATE AND CURRENT_DATE < ap.EXPIRED_DATE)
LEFT JOIN adm.ADM_APP aa ON (aa.PERSON_ID = ga.PERSON_ID)
WHERE ga.PROGRAM in ('234060', '234062')
ORDER BY p.BYU_ID


-- Grad App Exam Scores
SELECT p.BYU_ID, st.CREDIT_INSTITUTION, st.TEST_TYPE, st.TEST_VERSION, st.TEST_DATE, sts.SCORE_TYPE, sts.TEST_SCORE
FROM STDRECS.STD_TEST_SCORES sts
JOIN STDRECS.STD_TESTS st ON (st.PERSON_ID = sts.PERSON_ID AND TEST_SOURCE = 'S')
JOIN pro.PERSON p ON (p.PERSON_ID = st.PERSON_ID)
JOIN stdprgm.STD_PROGRAM sp ON (sp.PERSON_ID = st.PERSON_ID AND CURRENT_DATE >= sp.EFFECTIVE_DATE AND CURRENT_DATE < sp.EXPIRED_DATE)
JOIN STDPRGM.PROGRAM_ID_CODE_MAP pcm ON (pcm.PROGRAM_ID = sp.PROGRAM_ID)
WHERE pcm.PROGRAM_CODE in ('234060', '234062')
ORDER BY p.BYU_ID

-- Grad App Education
SELECT p.BYU_ID, 'N' AS transfer_flag, sp.DEGREE, apl.MAJOR_DESC AS degree_desc, 
CASE sp.PROGRAM_STATUS WHEN 'A' THEN 'ACTIVE' WHEN 'C' THEN 'COMPLETED' WHEN 'E' THEN 'EXPIRED' END AS PROGRAM_STATUS, 
sp.PROGRAM_ID, sp.PROGRAM_TYPE, apl.MAJOR_DESC AS program_desc, apl.SPEC_DESC, apl.ACADEMIC_UNIT_ID, sp.CREDIT_INSTITUTION AS academic_unit_desc,
sss.TOT_GPA, sss. BYU_GPA, 0 AS TRNS_GPA, SUBSTR(sd.GRADUATION_YEAR_TERM,1,4) AS grad_date, sp.CREDIT_INSTITUTION AS institution
FROM stdprgm.STD_PROGRAM sp
JOIN pro.PERSON p ON (p.PERSON_ID = sp.PERSON_ID)
JOIN stdprgm.PROGRAM_ID_CODE_MAP pcm ON (pcm.PROGRAM_ID = sp.PROGRAM_ID)
JOIN stdprgm.STD_DEGREE sd ON (sd.PERSON_ID = p.PERSON_ID)
JOIN stdprgm.ACAD_PROGRAM_LIST apl ON (sp.PROGRAM_ID = apl.MAJOR_PROGRAM_ID)
JOIN acadunit.ACADEMIC_UNIT au ON (au.ACADEMIC_UNIT_ID = apl.ACADEMIC_UNIT_ID AND CURRENT_DATE < au.EXPIRED_DATE)
JOIN ODS.student_stat_summary sss ON (sss.PERSON_ID = p.PERSON_ID)
WHERE sd.degree_status = 'COMPLETED' AND pcm.PROGRAM_CODE in ('234060', '234062')
UNION
SELECT p.BYU_ID, 'Y' AS transfer_flag, std.DEGREE, std.DEGREE_MAJOR AS degree_desc, 'COMPLETED' AS DEGREE_STATUS, std.COLLEGE_CODE AS PROGRAM_ID,
'-' AS PROGRAM_TYPE, std.DEGREE_MAJOR AS program_desc, ' ' AS SPEC_DESC, ' ' AS ACADEMIC_UNIT_ID, ' ' AS academic_unit_desc,
0 AS TOT_GPA, 0 AS BYU_GPA, std.DEGREE_GPA, SUBSTR(std.DEGREE_DATE,1,4) AS grad_date, tc.COLLEGE_NAME_LONG AS institution 
FROM xfereval.STD_TRAN_DEGREE std
JOIN pro.PERSON p ON (p.PERSON_ID = std.PERSON_ID) 
JOIN XFEREVAL.TRANSFER_COLLEGES tc ON (tc.COLLEGE_CODE = std.COLLEGE_CODE)
WHERE std.PERSON_ID IN (
    SELECT DISTINCT(p.PERSON_ID)
    FROM stdprgm.STD_PROGRAM sp
    JOIN pro.PERSON p ON (p.PERSON_ID = sp.PERSON_ID)
    JOIN stdprgm.PROGRAM_ID_CODE_MAP pcm ON (pcm.PROGRAM_ID = sp.PROGRAM_ID)
    JOIN stdprgm.STD_DEGREE sd ON (sd.PERSON_ID = p.PERSON_ID)
    JOIN stdprgm.ACAD_PROGRAM_LIST apl ON (sp.PROGRAM_ID = apl.MAJOR_PROGRAM_ID)
    JOIN acadunit.ACADEMIC_UNIT au ON (au.ACADEMIC_UNIT_ID = apl.ACADEMIC_UNIT_ID AND CURRENT_DATE < au.EXPIRED_DATE)
    JOIN ODS.student_stat_summary sss ON (sss.PERSON_ID = p.PERSON_ID)
    WHERE sd.degree_status = 'COMPLETED' AND pcm.PROGRAM_CODE in ('234060', '234062')
    )

-- Grad Application Employment
SELECT p.BYU_ID, we.EMPLOYER_NAME, we.EMPLOYER_LOCATION, we.EMPLOYED_FROM, we.EMPLOYED_TO, we.DUTIES,
    CASE WHEN we.SEQ_NUM = '1' THEN 'Y' ELSE 'N' END AS current_job,
    ROUND(MONTHS_BETWEEN(CASE WHEN EMPLOYED_TO IS NOT NULL THEN EMPLOYED_TO ELSE SYSDATE END, EMPLOYED_FROM)) AS MONTHS_EXP
FROM adm.WORK_EXPR we
JOIN pro.PERSON p ON (p.PERSON_ID = we.PERSON_ID)
JOIN stdprgm.STD_PROGRAM sp ON (sp.PERSON_ID = p.PERSON_ID)
JOIN stdprgm.PROGRAM_ID_CODE_MAP pcm ON (pcm.PROGRAM_ID = sp.PROGRAM_ID)
WHERE pcm.PROGRAM_CODE in ('234060', '234062')
AND we.EMPLOYER_NAME IS NOT NULL
AND we.EMPLOYED_FROM IS NOT NULL
ORDER BY p.BYU_ID

-- INSTITUTION    
SELECT sp.CREDIT_INSTITUTION AS institution
FROM stdprgm.STD_PROGRAM sp
JOIN pro.PERSON p ON (p.PERSON_ID = sp.PERSON_ID)
JOIN stdprgm.PROGRAM_ID_CODE_MAP pcm ON (pcm.PROGRAM_ID = sp.PROGRAM_ID)
JOIN stdprgm.STD_DEGREE sd ON (sd.PERSON_ID = p.PERSON_ID)
JOIN stdprgm.ACAD_PROGRAM_LIST apl ON (sp.PROGRAM_ID = apl.MAJOR_PROGRAM_ID)
JOIN acadunit.ACADEMIC_UNIT au ON (au.ACADEMIC_UNIT_ID = apl.ACADEMIC_UNIT_ID AND CURRENT_DATE < au.EXPIRED_DATE)
JOIN ODS.student_stat_summary sss ON (sss.PERSON_ID = p.PERSON_ID)
WHERE sd.degree_status = 'COMPLETED' AND pcm.PROGRAM_CODE in ('234060', '234062')
UNION
SELECT DISTINCT tc.COLLEGE_NAME_LONG AS institution 
FROM xfereval.STD_TRAN_DEGREE std
JOIN pro.PERSON p ON (p.PERSON_ID = std.PERSON_ID) 
JOIN XFEREVAL.TRANSFER_COLLEGES tc ON (tc.COLLEGE_CODE = std.COLLEGE_CODE)
WHERE std.PERSON_ID IN (
    SELECT DISTINCT(p.PERSON_ID)
    FROM stdprgm.STD_PROGRAM sp
    JOIN pro.PERSON p ON (p.PERSON_ID = sp.PERSON_ID)
    JOIN stdprgm.PROGRAM_ID_CODE_MAP pcm ON (pcm.PROGRAM_ID = sp.PROGRAM_ID)
    JOIN stdprgm.STD_DEGREE sd ON (sd.PERSON_ID = p.PERSON_ID)
    JOIN stdprgm.ACAD_PROGRAM_LIST apl ON (sp.PROGRAM_ID = apl.MAJOR_PROGRAM_ID)
    JOIN acadunit.ACADEMIC_UNIT au ON (au.ACADEMIC_UNIT_ID = apl.ACADEMIC_UNIT_ID AND CURRENT_DATE < au.EXPIRED_DATE)
    JOIN ODS.student_stat_summary sss ON (sss.PERSON_ID = p.PERSON_ID)
    WHERE sd.degree_status = 'COMPLETED' AND pcm.PROGRAM_CODE in ('234060', '234062')
    )


-- ACADEMIC UNITS
SELECT DISTINCT apl.ACADEMIC_UNIT_ID, sp.CREDIT_INSTITUTION AS academic_unit_desc
FROM stdprgm.STD_PROGRAM sp
JOIN pro.PERSON p ON (p.PERSON_ID = sp.PERSON_ID)
JOIN stdprgm.PROGRAM_ID_CODE_MAP pcm ON (pcm.PROGRAM_ID = sp.PROGRAM_ID)
JOIN stdprgm.STD_DEGREE sd ON (sd.PERSON_ID = p.PERSON_ID)
JOIN stdprgm.ACAD_PROGRAM_LIST apl ON (sp.PROGRAM_ID = apl.MAJOR_PROGRAM_ID)
JOIN acadunit.ACADEMIC_UNIT au ON (au.ACADEMIC_UNIT_ID = apl.ACADEMIC_UNIT_ID AND CURRENT_DATE < au.EXPIRED_DATE)
JOIN ODS.student_stat_summary sss ON (sss.PERSON_ID = p.PERSON_ID)
WHERE sd.degree_status = 'COMPLETED' AND pcm.PROGRAM_CODE in ('234060', '234062')
UNION
SELECT '-' AS ACADEMIC_UNIT_ID, '-' AS academic_unit_desc
FROM xfereval.STD_TRAN_DEGREE std
JOIN pro.PERSON p ON (p.PERSON_ID = std.PERSON_ID) 
JOIN XFEREVAL.TRANSFER_COLLEGES tc ON (tc.COLLEGE_CODE = std.COLLEGE_CODE)
WHERE std.PERSON_ID IN (
    SELECT DISTINCT(p.PERSON_ID)
    FROM stdprgm.STD_PROGRAM sp
    JOIN pro.PERSON p ON (p.PERSON_ID = sp.PERSON_ID)
    JOIN stdprgm.PROGRAM_ID_CODE_MAP pcm ON (pcm.PROGRAM_ID = sp.PROGRAM_ID)
    JOIN stdprgm.STD_DEGREE sd ON (sd.PERSON_ID = p.PERSON_ID)
    JOIN stdprgm.ACAD_PROGRAM_LIST apl ON (sp.PROGRAM_ID = apl.MAJOR_PROGRAM_ID)
    JOIN acadunit.ACADEMIC_UNIT au ON (au.ACADEMIC_UNIT_ID = apl.ACADEMIC_UNIT_ID AND CURRENT_DATE < au.EXPIRED_DATE)
    JOIN ODS.student_stat_summary sss ON (sss.PERSON_ID = p.PERSON_ID)
    WHERE sd.degree_status = 'COMPLETED' AND pcm.PROGRAM_CODE in ('234060', '234062')
    )

-- BYU ACADEMIC PROGRAMS
SELECT DISTINCT sp.PROGRAM_ID, apl.MAJOR_DESC AS program_desc, sp.DEGREE, apl.MAJOR_DESC AS degree_desc,
sp.PROGRAM_TYPE, apl.SPEC_DESC, apl.ACADEMIC_UNIT_ID, sp.CREDIT_INSTITUTION AS academic_unit_desc,
sp.CREDIT_INSTITUTION AS institution
FROM stdprgm.STD_PROGRAM sp
JOIN pro.PERSON p ON (p.PERSON_ID = sp.PERSON_ID)
JOIN stdprgm.PROGRAM_ID_CODE_MAP pcm ON (pcm.PROGRAM_ID = sp.PROGRAM_ID)
JOIN stdprgm.STD_DEGREE sd ON (sd.PERSON_ID = p.PERSON_ID)
JOIN stdprgm.ACAD_PROGRAM_LIST apl ON (sp.PROGRAM_ID = apl.MAJOR_PROGRAM_ID)
JOIN acadunit.ACADEMIC_UNIT au ON (au.ACADEMIC_UNIT_ID = apl.ACADEMIC_UNIT_ID AND CURRENT_DATE < au.EXPIRED_DATE)
JOIN ODS.student_stat_summary sss ON (sss.PERSON_ID = p.PERSON_ID)
WHERE sd.degree_status = 'COMPLETED' AND pcm.PROGRAM_CODE in ('234060', '234062')

-- TRANSFERED PROGRAMS
SELECT DISTINCT std.COLLEGE_CODE AS PROGRAM_ID, std.DEGREE_MAJOR AS program_desc, std.DEGREE, std.DEGREE_MAJOR AS degree_desc,
'TRFR' AS PROGRAM_TYPE, '-' AS SPEC_DESC, '-' AS ACADEMIC_UNIT_ID, '-' AS academic_unit_desc,
tc.COLLEGE_NAME_LONG AS institution 
FROM xfereval.STD_TRAN_DEGREE std
JOIN pro.PERSON p ON (p.PERSON_ID = std.PERSON_ID) 
JOIN XFEREVAL.TRANSFER_COLLEGES tc ON (tc.COLLEGE_CODE = std.COLLEGE_CODE)
WHERE std.PERSON_ID IN (
    SELECT DISTINCT(p.PERSON_ID)
    FROM stdprgm.STD_PROGRAM sp
    JOIN pro.PERSON p ON (p.PERSON_ID = sp.PERSON_ID)
    JOIN stdprgm.PROGRAM_ID_CODE_MAP pcm ON (pcm.PROGRAM_ID = sp.PROGRAM_ID)
    JOIN stdprgm.STD_DEGREE sd ON (sd.PERSON_ID = p.PERSON_ID)
    JOIN stdprgm.ACAD_PROGRAM_LIST apl ON (sp.PROGRAM_ID = apl.MAJOR_PROGRAM_ID)
    JOIN acadunit.ACADEMIC_UNIT au ON (au.ACADEMIC_UNIT_ID = apl.ACADEMIC_UNIT_ID AND CURRENT_DATE < au.EXPIRED_DATE)
    JOIN ODS.student_stat_summary sss ON (sss.PERSON_ID = p.PERSON_ID)
    WHERE sd.degree_status = 'COMPLETED' AND pcm.PROGRAM_CODE in ('234060', '234062')
    )

-- DEGREES
SELECT sp.DEGREE, apl.MAJOR_DESC AS degree_desc
FROM stdprgm.STD_PROGRAM sp
JOIN pro.PERSON p ON (p.PERSON_ID = sp.PERSON_ID)
JOIN stdprgm.PROGRAM_ID_CODE_MAP pcm ON (pcm.PROGRAM_ID = sp.PROGRAM_ID)
JOIN stdprgm.STD_DEGREE sd ON (sd.PERSON_ID = p.PERSON_ID)
JOIN stdprgm.ACAD_PROGRAM_LIST apl ON (sp.PROGRAM_ID = apl.MAJOR_PROGRAM_ID)
JOIN acadunit.ACADEMIC_UNIT au ON (au.ACADEMIC_UNIT_ID = apl.ACADEMIC_UNIT_ID AND CURRENT_DATE < au.EXPIRED_DATE)
JOIN ODS.student_stat_summary sss ON (sss.PERSON_ID = p.PERSON_ID)
WHERE sd.degree_status = 'COMPLETED' AND pcm.PROGRAM_CODE in ('234060', '234062')
UNION
SELECT std.DEGREE, std.DEGREE_MAJOR AS degree_desc
FROM xfereval.STD_TRAN_DEGREE std
JOIN pro.PERSON p ON (p.PERSON_ID = std.PERSON_ID) 
JOIN XFEREVAL.TRANSFER_COLLEGES tc ON (tc.COLLEGE_CODE = std.COLLEGE_CODE)
WHERE std.PERSON_ID IN (
    SELECT DISTINCT(p.PERSON_ID)
    FROM stdprgm.STD_PROGRAM sp
    JOIN pro.PERSON p ON (p.PERSON_ID = sp.PERSON_ID)
    JOIN stdprgm.PROGRAM_ID_CODE_MAP pcm ON (pcm.PROGRAM_ID = sp.PROGRAM_ID)
    JOIN stdprgm.STD_DEGREE sd ON (sd.PERSON_ID = p.PERSON_ID)
    JOIN stdprgm.ACAD_PROGRAM_LIST apl ON (sp.PROGRAM_ID = apl.MAJOR_PROGRAM_ID)
    JOIN acadunit.ACADEMIC_UNIT au ON (au.ACADEMIC_UNIT_ID = apl.ACADEMIC_UNIT_ID AND CURRENT_DATE < au.EXPIRED_DATE)
    JOIN ODS.student_stat_summary sss ON (sss.PERSON_ID = p.PERSON_ID)
    WHERE sd.degree_status = 'COMPLETED' AND pcm.PROGRAM_CODE in ('234060', '234062')
    )